name: Unit tests

on:
    pull_request:
        branches: [main]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install packages
              uses: actions/setup-node@v4
              with:
                  node-version: "18.x"

            - name: Cache node modules
              id: cache-node-modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: node_modules-${{hashFiles('package.lock.json')}}

            - name: Install dependencies
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm ci && npm i hardhat-gas-reporter

            - name: Setup .env config
              run: cp .env.example .env

            - name: Run Tests
              run: npx hardhat test
