name: Unit tests

on:
    pull_request:
        branches: [main]
        paths:
            - "contracts/**"
            - "test/**"

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install packages
              uses: actions/setup-node@v4
              with:
                  node-version: "18.x"

            - name: Cache node modules
              id: cache-nodemodules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  # caching node_modules
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Install dependencies
              if: steps.cache-nodemodules.outputs.cache-hit != 'true'
              run: npm ci && npm i hardhat-gas-reporter

            - name: Setup .env config
              run: cp .env.example .env

            - name: Run Tests
              run: npx hardhat test
